### ISSUE TITLE
Allow more refined request search

### ISSUE THREAD

**Issue by dev-in-disguise** [WireMock-Net/WireMockInspector#13]
Imagine if I have an API that has the following endpoints:

* `POST api/user`
* `GET api/users`

If I now want to filter out only the `POST api/user` requests in WireMockInspector I'll always receive also the `GET api/users` request since the current implementation does a `Path.Contains(x.Term)` check. 

It would be great to have another request matching algorithm in place for this. 2 possible ones come to my mind:

1. `Exactly matched`: would basically result in a `Path.Equals(x.Term)` check.
2. `Regex matched`: performs a match based on a user defined regex

Though I usually dislike Regex I think I might personally prefer that option here since it could be tiresome having to write out the whole path.

**Comment by cezarypiatek** [comment]
What do you think about adding lucene query syntax? https://lucene.apache.org/core/2_9_4/queryparsersyntax.html
You could write queries like

```
method: POST and path:api/user
```

**Comment by dev-in-disguise** [comment]
That actually sounds like a brilliant idea!

The fact alone to use lucene is awesome and I personally loved it while using Kibana. So that's already a plus.

And giving the possibility to also query on the method itself is even better.

So all in all I really do like your proposal the most of all options so far

**Comment by cezarypiatek** [comment]
I will try to incorporate Lucene into WireMockInspector

**Comment by cezarypiatek** [comment]
Please try the latest version

![image](https://github.com/WireMock-Net/WireMockInspector/assets/7759991/620ffebb-00b9-4851-a3d3-d48d3ad81c68)
