### ISSUE TITLE
Small improvement to request body json diff

### ISSUE THREAD

**Issue by robertlyson** [WireMock-Net/WireMockInspector#26]
Seems like json diff doesn't recognize order of nested object properties
![image](https://github.com/WireMock-Net/WireMockInspector/assets/2392583/f9377e88-d422-452d-9c01-c29462ad0ca3)

Above is request body.

**Comment by robertlyson** [comment]
Strange part is .. sometimes it works just great, maybe I'm missing something
![image](https://github.com/WireMock-Net/WireMockInspector/assets/2392583/9001797e-4a66-4069-9c62-53e1083d6869)

**Comment by cezarypiatek** [comment]
This is intended behavior - before executing diff, both JSON payloads are sorted to make the diff easier to read.  Do you have usecases when properties order matter?

**Comment by robertlyson** [comment]
When I mock my calls to graphql endpoint I do it like this

```
private void Graphql((IRequestBuilder request, IResponseBuilder response) server)
{
    server.request
        .UsingMethod("POST")
        .WithPath("/graphql")
        .WithHeader(name: "Accept", pattern: "application/graphql-response+json, application/json")
        .WithHeader(name: "Authorization", pattern: "token_type access_token")
        .WithHeader(name: "Content-Type", pattern: "application/json; charset=utf-8")
        .WithBodyAsJson(new
        {
            query =
                "some query",
            variables = new
            {
                spaceId = 981,
                take = 100,
                skip = 0,
            },
            operationName = (string) null!,
            extensions = (string) null!
        });

    server.response
        .WithBody(Response());
}
```

and by accident I just reorder my variables so it doesn't match actual call to graphql endpoint.
Becasue of this Wiremock is not returning any data
![image](https://github.com/WireMock-Net/WireMockInspector/assets/2392583/39f94682-5a08-4cc4-9c8a-3ee2bb1371e8)
There is indication that the request body didn't match which is correct
![image](https://github.com/WireMock-Net/WireMockInspector/assets/2392583/8f0773e5-7027-4d47-b2cc-b0f055856fb0)
but diff doesn't show that becasue all of the props are sorted :)
![image](https://github.com/WireMock-Net/WireMockInspector/assets/2392583/f4583623-54ec-4c87-9a1e-0970595c74fb)

**Comment by cezarypiatek** [comment]
Maybe you should try JsonPartialWildcardMatcher https://github.com/WireMock-Net/WireMock.Net/wiki/Request-Matching-JsonPartialWildcardMatcher
I'm using it for GraphQL mocks and I've never had a problem with properties order.

Let me know if that solved your problem

**Comment by robertlyson** [comment]
Thanks for the suggestion, will give it a try.
