### ISSUE TITLE
Default Port

### ISSUE THREAD

**Issue by StefH** [WireMock-Net/WireMockInspector#5]
Maybe change the default port to 9091 instead of 1080.

**Comment by cezarypiatek** [comment]
What's the default behavior when the WireMock server is started without providing the port explicitly?  Is it run on 9091 or a random port?

**Comment by StefH** [comment]
Default documentation for Docker uses 9091. https://github.com/WireMock-Net/WireMock.Net-docker




Default port for standalone/ dotnet tool is http://*:9091/

**Comment by cezarypiatek** [comment]
OK, I will change it to 9091, but it would be handy to remember/persist the last user choice.
