### ISSUE TITLE
Stopping a test and displaying the GUI for a mock

### ISSUE THREAD

**Issue by grzesiek-galezowski** [WireMock-Net/WireMockInspector#7]
Hi!

As discussed on twitter, I would like to use the inspector in the following way:

Let's say I have a test:

```csharp
using var wiremock = WireMockServer.Start();

//do something

//assert something
```

and I want to debug it because something is not being matched, I'd like to do something like this:

```csharp
using var wiremock = WireMockServer.StartWithAdminInterface();

//do something

wiremock.ShowInspector();

//assert something
```

and the like `wiremock.ShowInspector();` would block the test and open the inspector with mappings loaded for this mock.

I think it could be done in two ways:

1) Have the test reference the inspector as a library
2) Using process API to start new inspector and wait for exit

I guess the second approach could be better because:
1) No big changes required to the inspector code
2) Process API is relatively simple for trivial use cases, somebody could write such extension method in their codebase.

But I believe that for both approaches, it would be necessary for the inspector to allow passing a wiremock api url via program parameter (e.g. commandline arg). With approach 2, this could be the only required change to enable this scenario.

**Comment by cezarypiatek** [comment]
I've started working on it. I will let you know when I need your help.

**Comment by cezarypiatek** [comment]
I've just released a new version that allows for passing AdmingUrl as startup parameter. Sample usage:

```shell
wiremockinspector attach --adminUrl http://localhost:1088 --autoLoad --instanceName Test
```

The minimal working version of the Inspect method can look as follows

```cs
public static class WireMockServerExtensions
{
    public static void Inspect(this WireMockServer wireMock, [CallerMemberName] string callerMethodName = "")
    {
        if (wireMock.IsStarted == false)
            throw new InvalidOperationException("WireMock service is not started");

        if (wireMock.Mappings.Any(x => x.IsAdminInterface) == false)
            throw new InvalidOperationException("WireMock service is not started with Admin interface");

        var inspectorProcess = Process.Start(new ProcessStartInfo
        {
            FileName = "wiremockinspector",
            Arguments = $"attach --adminUrl {wireMock.Url} --autoLoad --instanceName {callerMethodName}",
            UseShellExecute = false
        });

        inspectorProcess?.WaitForExit();
    }
}
```

I already tested it and it works great. Please let me know if the current solution provides the expected experience.
In the next step we need to decide how to distribute the `Inspect` method. I'm seeing here two options:
- Option 1: Create a separate Nuget package for that purpose
- Option 2: Include it in the original WireMock-Net package.

@StefH  what do you think about `Option 2` ?

**Comment by StefH** [comment]
Another idea:
- Just use the `IWireMockServer` interface instead of the `WireMockServer` class.
- Add this extension method to your project
- And just add a reference to `WireMock.Net.Abstractions` NuGet in your project.

Just like this one:
https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net.OpenApiParser/WireMock.Net.OpenApiParser.csproj

**Comment by cezarypiatek** [comment]
Thanks for the remarks regarding the wire mock interface.

If I add the extension method to my project I need to release a separate nuget package. The current one is for dotnet tool not sure if a single package can contain dotnet tool and project references. I thought that If we added the method to the original WireMock package, the discovery would be much easier.

**Comment by StefH** [comment]
@cezarypiatek @grzesiek-galezowski 

> and the like `wiremock.ShowInspector();` would block the test and open the inspector with mappings loaded for this mock.

This looks a bit like the behavior from https://github.com/VerifyTests/Verify

**Comment by StefH** [comment]
> Thanks for the remarks regarding the wire mock interface.
> 
> If I add the extension method to my project I need to release a separate nuget package. The current one is for dotnet tool not sure if a single package can contain dotnet tool and project references. I thought that If we added the method to the original WireMock package, the discovery would be much easier.

The current wiremockinspector nuget can be referenced in another project, although _only_ for .NET 6.

So in that case a separate NuGet would be better. More like the https://github.com/VerifyTests/Verify is doing.
The name from the NuGet could be:
- WireMockInspector.Extensions.WireMock.Net
- WireMock.Net.Extensions.WireMockInspector
- ???

Reason for not integrating in WireMock.Net is security, because a process is started, and if a different application with the same name exists, maybe wrong exe will be started.

**Comment by grzesiek-galezowski** [comment]
Btw, tried the new version with the proposed extension method and it works great. 

@cezarypiatek if you don't want to maintain another package, an option would be to publish the code snippet in the inspector documentation and the user would have to copy-paste it. May not be optimal but may also save you some maintenance burden. Just a thought.

@StefH My use case is simpler than Verify's one, though there are some similarities. I just want to be able to quickly change the code when debugging to show me the mappings in a more user-friendly way. Also, a side-use-case would be presentations of wiremock to engineers who don't know it already - I think when I do demos, I will hook the inspector this way and every time I run a test with modifications, people I train will be able to see exactly how wiremock applied the matching rules in a friendly way.

**Comment by cezarypiatek** [comment]
@StefH  I tried to use `IWireMockServer`  instead `WireMockServer` of but it looks like there's no way to determine if WireMock has enabled admin API, so I won't be able to perform the following check which might be very helpful

```cs

        if (wireMock.Mappings.Any(x => x.IsAdminInterface) == false)
            throw new InvalidOperationException("WireMock service is not started with Admin interface");
```

Is there a more than one implementation of `IWireMockServer` or it's just a matter of the dependency that the `WireMockServer` brings with itself?

**Comment by StefH** [comment]
Easiest would be that I add a new property `IsStartedWithAdminInterface` to the `IWireMockServer`.

However do you really want to know if the http-server is started and it's started as admin?
Or just that it's started with admin (http server could not yet be started)

**Comment by cezarypiatek** [comment]
I changed my mind. The WireMockInspect will notify user if he tries to attach the inspector to the WireMock server without an admin interface. It should be enough.

![image](https://user-images.githubusercontent.com/7759991/236619174-ee342a93-d5c4-4ea2-b1e4-6ef5ef217891.png)

**Comment by cezarypiatek** [comment]
@StefH I named the new package `WireMock.Net.Extensions.WireMockInspector`  but it looks like the prefix is reserved. Can you give me the appropriate permission to this prefix or generated a dedicated nuget KEY from your account?

```
error: Response status code does not indicate success: 409 (This package ID has been reserved. Please request access to upload to this reserved namespace from the owner of the reserved prefix, or re-upload the package with a different ID. Go to https://docs.microsoft.com/nuget/reference/id-prefix-reservation learn more about Package ID prefix reservation.).
```

**Comment by StefH** [comment]
Option 1 is available in preview:
1.5.23-ci-17362

**Comment by StefH** [comment]
> @StefH I named the new package `WireMock.Net.Extensions.WireMockInspector` but it looks like the prefix is reserved. Can you give me the appropriate permission to this prefix or generated a dedicated nuget KEY from your account?
> 
> ```
> error: Response status code does not indicate success: 409 (This package ID has been reserved. Please request access to upload to this reserved namespace from the owner of the reserved prefix, or re-upload the package with a different ID. Go to https://docs.microsoft.com/nuget/reference/id-prefix-reservation learn more about Package ID prefix reservation.).
> ```

It depends if you plan to release a lot of changes for this packages, else it's maybe easier to add this package to the main project and let the default CI/CD build + publish to NuGet task take care of this.

**Comment by StefH** [comment]
Or I can ask NuGet to delegate the prefix `WireMock.Net.Extensions.WireMockInspector` to your account.

**Comment by cezarypiatek** [comment]
Both options are fine to me. As you are the prefix owner, please decide.

**Comment by StefH** [comment]
I'll send email to NuGet. I keep you informed.

**Comment by StefH** [comment]
Email has been sent to NuGet.

Another question about this code:

What happens if there is no wiremockinspector tool installed?
Maybe it's useful to display a message or throw exception with instructions how to install wiremockinspector ?

``` c#
var inspectorProcess = Process.Start(new ProcessStartInfo
        {
            FileName = "wiremockinspector",
            Arguments = $"attach --adminUrl {wireMock.Url} --autoLoad --instanceName {callerMethodName}",
            UseShellExecute = false
        });

        inspectorProcess?.WaitForExit();
```

**Comment by cezarypiatek** [comment]
If the `WireMockInspect` is not installed then `Process.Start` will throw an exception about non-existing file/executable.
Ofc I can catch it and wrap it in something more meaningful/descriptive.

**Comment by StefH** [comment]
I think that catching the exception and displaying a message (including a link to this project or instructions to install it) would be helpful.

**Comment by StefH** [comment]
@cezarypiatek 
I got a message back from NuGet that WireMock.Net.Extensions.WireMockInspector is assigned/reserved to you, can you try uploading it?

**Comment by cezarypiatek** [comment]
@StefH  I managed to upload nuget package under WireMock.Net.Extensions.WireMockInspector  name. Thanks for your help.

@grzesiek-galezowski  can you test te nuget package? Any feedback is welcome.

**Comment by grzesiek-galezowski** [comment]
Hi, I'm getting something like this:

`System.TypeLoadException : Method 'get_IsStartedWithAdminInterface' in type 'WireMock.Server.WireMockServer' from assembly 'WireMock.Net, Version=1.5.23.0, Culture=neutral, PublicKeyToken=c8d65537854e1f03' does not have an implementation.`

My package dependencies:

```xml
  <ItemGroup>
    <PackageReference Include="Any" Version="9.2.1" />
    <PackageReference Include="FluentAssertions" Version="6.11.0" />
    <PackageReference Include="Flurl.Http" Version="3.2.4" />
    <PackageReference Include="LanguageExt.Core" Version="4.4.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="7.0.5" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
    <PackageReference Include="NSubstitute" Version="5.0.0" />
    <PackageReference Include="NSubstitute.Analyzers.CSharp" Version="1.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.4.2" />
    <PackageReference Include="NUnit.Analyzers" Version="3.6.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="3.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="WireMock.Net" Version="1.5.23" />
    <PackageReference Include="WireMock.Net.Extensions.WireMockInspector" Version="1.0.9" />
  </ItemGroup>
```

and here's the snipped I used:

```csharp
using var wiremock = WireMockServer.StartWithAdminInterface();

wiremock.Given(Request.Create().UsingGet()).RespondWith(Response.Create().WithStatusCode(HttpStatusCode.Accepted));

await wiremock.Url.AllowAnyHttpStatus().PostJsonAsync(new
{
  name = "Zenek"
});

wiremock.Inspect();
```

**Comment by StefH** [comment]
You need to remove your defined dependency on WireMock version 1.5.23:
`<PackageReference Include="WireMock.Net" Version="1.5.23" />`

Because the WireMock.Net.Extensions.WireMockInspector requires version 1.5.24

**Comment by grzesiek-galezowski** [comment]
bumping the version helped. @cezarypiatek what do you think about adding a note to the README that at least version 1.5.24 is required?

**Comment by StefH** [comment]
@grzesiek-galezowski 
This should not be needed because when you include WireMock.Net.Extensions.WireMockInspector alone, the correct version 1.5.24 is used.

(BTW: I would think that you got some compile warnings/errors in your project related to version 1.5.23)?

**Comment by grzesiek-galezowski** [comment]
Other than that, the package is working really well, thank you @StefH and @cezarypiatek! From my point of view, we can close this issue. What do you think?

**Comment by cezarypiatek** [comment]
Thanks for your collaboration and for testing. Issue closed.
